CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shaolins (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  genero TEXT DEFAULT 'masculino',
  level INTEGER DEFAULT 1,
  xp INTEGER DEFAULT 0,
  hp INTEGER DEFAULT 65,
  max_hp INTEGER DEFAULT 65,
  fuerza INTEGER DEFAULT 5,
  agilidad INTEGER DEFAULT 5,
  velocidad INTEGER DEFAULT 5,
  vitalidad INTEGER DEFAULT 0,
  combates_hoy INTEGER DEFAULT 0,
  ultimo_combate DATE,
  pending_level INTEGER DEFAULT 0,
  skin TEXT DEFAULT 'default',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS armas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shaolin_id INTEGER NOT NULL,
  nombre TEXT NOT NULL,
  nivel INTEGER DEFAULT 1,
  equipada INTEGER DEFAULT 0,
  FOREIGN KEY (shaolin_id) REFERENCES shaolins(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS habilidades (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shaolin_id INTEGER NOT NULL,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  efecto TEXT NOT NULL,
  nivel INTEGER DEFAULT 1,
  FOREIGN KEY (shaolin_id) REFERENCES shaolins(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS combates (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shaolin1_id INTEGER NOT NULL,
  shaolin2_id INTEGER NOT NULL,
  winner_id INTEGER,
  log TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (shaolin1_id) REFERENCES shaolins(id),
  FOREIGN KEY (shaolin2_id) REFERENCES shaolins(id)
);
