CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS brutos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  genero TEXT DEFAULT 'masculino',
  level INTEGER DEFAULT 1,
  xp INTEGER DEFAULT 0,
  hp INTEGER DEFAULT 65,
  max_hp INTEGER DEFAULT 65,
  fuerza INTEGER DEFAULT 5,
  agilidad INTEGER DEFAULT 5,
  velocidad INTEGER DEFAULT 5,
  combates_hoy INTEGER DEFAULT 0,
  ultimo_combate DATE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS armas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bruto_id INTEGER NOT NULL,
  nombre TEXT NOT NULL,
  tipo TEXT NOT NULL,
  dano_min INTEGER NOT NULL,
  dano_max INTEGER NOT NULL,
  equipada INTEGER DEFAULT 0,
  FOREIGN KEY (bruto_id) REFERENCES brutos(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS habilidades (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bruto_id INTEGER NOT NULL,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  efecto TEXT NOT NULL,
  FOREIGN KEY (bruto_id) REFERENCES brutos(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS mascotas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bruto_id INTEGER NOT NULL,
  nombre TEXT NOT NULL,
  tipo TEXT NOT NULL,
  hp INTEGER NOT NULL,
  ataque INTEGER NOT NULL,
  FOREIGN KEY (bruto_id) REFERENCES brutos(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS combates (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bruto1_id INTEGER NOT NULL,
  bruto2_id INTEGER NOT NULL,
  winner_id INTEGER,
  log TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (bruto1_id) REFERENCES brutos(id),
  FOREIGN KEY (bruto2_id) REFERENCES brutos(id)
);
